### ISSUE TITLE
How to use management.application.default_secrect?

### ISSUE THREAD

**Issue by m4rcs** [emqx/emqx-management#107]
I'm using the docker image of emqx to setup my broker and I wanted to use default_secret feature.

How I do see if the default secret is added? And what's the application id for the default secret?

**Comment by okool** [comment]
这个问题解决了么?
这个密码docker没法配置.

**Comment by turtleDeng** [comment]
Thanks for your suggestions, we will support in the next version.

**Comment by turtleDeng** [comment]
Thank you for your participation, the default APPID and secret have been added, please download the latest version to use.
