### ISSUE TITLE
Does the mgmt plugins support https?

### ISSUE THREAD

**Issue by RicardoHPeng** [emqx/emqx-management#15]
emqx version: emqxv3.0rc3
I found https options in the plugins mgmt config file, but couldn't find the  related docs in http://emqtt.com/docs/v3/rest.html. It seems emqx only support basic Authentication(with app id and secret) for REST API . So does the emqx-managerment plugins support the https access with certificates?

**Comment by Gilbert-Wong** [comment]
Of course you can, you can view the file `etc/plugins/emqx_management.conf` and find the options to configure your http ssl certifications.
