### ISSUE TITLE
can't create app in dashboard

### ISSUE THREAD

**Issue by YiuTerran** [emqx/emqx-management#171]
version: 4.0.2
platform: linux & macos

after i clicked `submit`, display `create success`. However, nothing will be list in the page.

I checked result with `emqx_ctl mgmt list`. It's created.

So, the real problem is that dashboard can't display app list.

**Comment by HJianBo** [comment]
Hi, @YiuTerran This is due to a recent packaging error, please re-download 4.0.2 of the official website.

**Comment by YiuTerran** [comment]
ok, that's not a big problem. thanks~
